Fix discovering executable files on macOS
macOS has BSD version of the find utility, which doesn't support the
`-perm /111` expression, but it does support `-perm +111` (which the
GNU version has since deprecated).

diff --git a/.github/workflows/scandir.yml b/.github/workflows/scandir.yml
--- a/.github/workflows/scandir.yml
+++ b/.github/workflows/scandir.yml
@@ -31,11 +31,15 @@ jobs:
 
     - name: Verify check
       run: |
-        expect="testfiles/scandir/run[[:space:]]me.bash"
+        expect1="testfiles/scandir/run[[:space:]]me.bash"
+        expect2="testfiles/scandir/exec"
         notexpect="testfiles/test.bash"
 
-        if [[ ! "${{ steps.one.outputs.files }}" =~ $expect ]];then
-          echo "::error:: Expected file $expect not found in ${{ steps.one.outputs.files }}"
+        if [[ ! "${{ steps.one.outputs.files }}" =~ $expect1 ]];then
+          echo "::error:: Expected file $expect1 not found in ${{ steps.one.outputs.files }}"
+          exit 1
+        if [[ ! "${{ steps.one.outputs.files }}" =~ $expect2 ]];then
+          echo "::error:: Expected file $expect2 not found in ${{ steps.one.outputs.files }}"
           exit 1
         elif [[ "${{ steps.one.outputs.files }}" =~ $notexpect ]];then
           echo "::error:: Expected file $notexpect found in ${{ steps.one.outputs.files }}"
