Add an option to check all executable scripts
By default, this action only checks extension-less executable scripts if they
have a known shebang such as `#!/usr/bin/env bash`. The new option
`all_scripts: true` relaxes the shebang regex pattern so that any executable
scripts are checked by shellcheck. This is suitable for repositories with
scripts that have unusal shebangs.

diff --git a/.github/workflows/scandir.yml b/.github/workflows/scandir.yml
--- a/.github/workflows/scandir.yml
+++ b/.github/workflows/scandir.yml
@@ -61,3 +61,19 @@ jobs:
           echo "::error:: Expected file $notexpect found in ${{ steps.two.outputs.files }}"
           exit 1
         fi
+
+    - name: Run ShellCheck
+      uses: ./
+      id: three
+      with:
+        scandir: './testfiles/scandir'
+        all_scripts: true
+
+    - name: Verify check
+      run: |
+        expect="testfiles/scandir/unknown-shebang"
+
+        if [[ ! "${{ steps.two.outputs.files }}" =~ $expect ]];then
+          echo "::error:: Expected file $expect not found in ${{ steps.two.outputs.files }}"
+          exit 1
+        fi
